### ISSUE TITLE
Adding DISQUS community comment section 

### ISSUE THREAD

**Issue by sanjay7178** [Sarath191181208/vitap-timetable-scheduler#1]

**Comment by sanjay7178** [comment]
DISQUS is enterprise , consider to look on [utterances](https://utteranc.es/ ) ie .. open source

**Comment by Sarath191181208** [comment]
I personally believe that project of this size wouldn't generally require that much attention and merges. The project wouldn't have a big community driven changes or rapid changes. Therefore having a separate tool to manage issues and wikis is kinda of over engineering it and isn't what I would like.

**Comment by sanjay7178** [comment]
> I personally believe that project of this size wouldn't generally require that much attention and merges. The project wouldn't have a big community driven changes or rapid changes. Therefore having a separate tool to manage issues and wikis is kinda of over engineering it and isn't what I would like.

No actually maintaining a community comment section , some would can get suggestions to choose a faculty , about choosing a course

**Comment by Sarath191181208** [comment]
Wouldn't it be much easier and better to maintain a discord/telegram channel and managing it with a bot ? As this isn't an enterprise solution.
