### ISSUE TITLE
For maintaining the timetable scheduler need a admin panel 

### ISSUE THREAD

**Issue by sanjay7178** [Sarath191181208/vitap-timetable-scheduler#2]

**Comment by sanjay7178** [comment]
Or we can make a github action upon uploading csv need to create a artifact and create a PR for preprocessed data

**Comment by sanjay7178** [comment]
Need a UUID or ULID based url approach for persistent/cached  timetable for sharing

**Comment by sanjay7178** [comment]
Need a semester drop down as well

**Comment by Sarath191181208** [comment]
> Or we can make a github action upon uploading csv need to create a artifact and create a PR for preprocessed data

We already have the python scripts required for this task to generate the json data and we could just copy paste the required data. As any errors generated by copy paste are caught by tsserver. So, therefore I having GitHub actions to having a PR open up and merging the ourselves wouldn't be better as the scope of the project is super focused.

**Comment by Sarath191181208** [comment]
> Need a UUID or ULID based url approach for persistent/cached timetable for sharing

How would you suggest that we should build this feature. I could think of two types of approaches:
- As you have suggested give UUID to a user and save his data and just send a sharable link. Requires a persistent store like DB. Firebase would be easier to manage as it automatically provides Google Oauth for authorisation.
- Save the data as query params and give the link. Have to research on this idea and the data we have to send is relatively big to usual links

**Comment by sanjay7178** [comment]
> > Need a UUID or ULID based url approach for persistent/cached timetable for sharing
> 
> How would you suggest that we should build this feature. I could think of two types of approaches:
> 
> * As you have suggested give UUID to a user and save his data and just send a sharable link. Requires a persistent store like DB. Firebase would be easier to manage as it automatically provides Google Oauth for authorisation.
> * Save the data as query params and give the link. Have to research on this idea and the data we have to send is relatively big to usual links

adhering to query params for entire data will be difficult , better to have a KV database like redis or cloudflare workers kv  for faster retrieval of json data with prior jwt/session based approach , or simple use firestore for long term data persistence

**Comment by Sarath191181208** [comment]
Good suggestion for a solution. But having another service to manage for a webapp that would be used once a semester is debatable.I'll try making query params happen.If that doesn't work, I am open to any other persistent store/ session management etc.
